# Generated by Django 3.1.7 on 2021-04-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20210402_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='https://place-hold.it/100x60', upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.URLField(default='https://place-hold.it/100x60'),
        ),
    ]
