# Generated by Django 3.1.7 on 2021-05-28 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0011_auto_20210528_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='grade',
            field=models.CharField(
                choices=[
                    ('TRAINEE', 'Стажер'),
                    ('JUNIOR', 'Джуниор'),
                    ('MIDDLE', 'Миддл'),
                    ('SENIOR', 'Сеньор'),
                    ('LEAD', 'Лид'),
                ],
                default='TRAINEE',
                max_length=20,
                verbose_name='Квалификация',
            ),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vacancies',
                to='vacancies.company',
                verbose_name='Компания',
            ),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies',
                                    to='vacancies.specialty', verbose_name='Специальность'),
        ),
    ]
