# Generated by Django 3.1.7 on 2021-05-28 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_auto_20210528_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True, verbose_name='Портфолио'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='resumes',
                to='vacancies.specialty',
                verbose_name='Специальность',
            ),
        ),
    ]
