# Generated by Django 3.1.7 on 2021-06-02 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_auto_20210528_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True, default='', verbose_name='Портфолио'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='resumes',
                to='vacancies.specialty',
                verbose_name='Специализация',
            ),
        ),
    ]
